package cn.ac.testcase;// Generated by Selenium IDE

import cn.ac.base.DriverBase;
import org.openqa.selenium.*;
import org.openqa.selenium.interactions.Actions;
import org.testng.annotations.Test;

public class Oolutest extends DriverBase {

    @Test
    public void test11() {

//        ((JavascriptExecutor) driver).executeScript("Page.addScriptToEvaluateOnNewDocument, {" +
//                "  source: " +
//                "    Object.defineProperty(navigator, 'webdriver', {" +
//                "      get: () => undefined" +
//                "    })" +
//                "  " +
//                "}");
        driver.get("https://moc.oocl.com/party/cargotracking/ct_search_from_other_domain.jsf?ANONYMOUS_BEHAVIOR=BUILD_UP&domainName=PARTY_DOMAIN&ENTRY_TYPE=OOCL&ENTRY=MCC&ctSearchType=BC&ctShipmentNumber=");
//        ((JavascriptExecutor) driver).executeScript("Page.addScriptToEvaluateOnNewDocument, {" +
//                "  source: " +
//                "    Object.defineProperty(navigator, 'webdriver', {" +
//                "      get: () => undefined" +
//                "    })" +
//                "  " +
//                "}");
//        try {
//            Thread.sleep(30000);
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        }
        System.out.println(driver.getPageSource());
//        driver.manage().window().setSize(new Dimension(974, 1040));
        {
            WebElement element = driver.findElement(By.id("nc_1_n1z"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.id("nc_1_n1z")).click();
    }
}
