package cn.ac.handlepage;

// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.testng.annotations.Test;

import cn.ac.base.DriverBase;

public class SearchTestCaseTest extends DriverBase {

	@Test
	public void searchTestCase() {
		driver.get("http://wzg02.shineway-soft.com/public/saas/sam/admin/main/html/main.html");
		driver.manage().window().setSize(new Dimension(945, 1020));
		driver.findElement(By.name("login_user")).click();
		driver.findElement(By.name("login_user")).sendKeys("Super");
		driver.findElement(By.cssSelector(".login-form-top > li")).click();
		driver.findElement(By.name("login_pas")).click();
		driver.findElement(By.name("login_pas")).sendKeys("Super");
		driver.findElement(By.cssSelector(".login-sub")).click();
//		js.executeScript("window.scrollTo(0,0)");
		driver.findElement(By.cssSelector(".platformmune-list > li:nth-child(3) > span")).click();
		{
			WebElement element = driver.findElement(By.xpath("//span[contains(.,\'基础数据维护\')]"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.xpath("//li[24]"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		driver.findElement(By.cssSelector(".platformmune-active")).click();
		driver.findElement(By.cssSelector(".searchtoolbar-search-span")).click();
	}
}
